base_model: unsloth/Llama-3.2-3B
dtype: float16
merge_method: ties
models:
- model: dphn/Dolphin3.0-Llama3.2-3B
  parameters:
    density: 0.5
    weight: 0.5
- model: EpistemeAI/Llama-3.2-3B-Agent007-Coder
  parameters:
    density: 0.5
    weight: 0.5
parameters:
  normalize: true
