base_model: HuggingFaceTB/SmolLM2-360M
dtype: float32
merge_method: ties
models:
- model: prithivMLmods/SmolLM2-CoT-360M
  parameters:
    density: 0.5
    weight: 0.5
- model: Masorian06/SmolLM2-360M-Rickified
  parameters:
    density: 0.5
    weight: 0.5
parameters:
  normalize: true
