base_model: HuggingFaceTB/SmolLM2-360M
dtype: float32
merge_method: ties
models:
- model: qiuyu8290/SmolLM2-360M-sft-math-gsm8k
  parameters:
    density: 0.5
    weight: 0.5
- model: HuggingFaceTB/SmolLM2-360M-Instruct
  parameters:
    density: 0.5
    weight: 0.5
parameters:
  normalize: true
